name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Set up environment variables for AppSheet API keys
        run: |
          echo "APPSHEET_API_KEY_1=${{ secrets.APPSHEET_API_KEY_1 }}" >> $GITHUB_ENV
          echo "APPSHEET_API_KEY_2=${{ secrets.APPSHEET_API_KEY_2 }}" >> $GITHUB_ENV
          echo "APPSHEET_API_KEY_3=${{ secrets.APPSHEET_API_KEY_3 }}" >> $GITHUB_ENV
          echo "APPSHEET_API_KEY_4=${{ secrets.APPSHEET_API_KEY_4 }}" >> $GITHUB_ENV

      - name: Build the app
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        run: |
          # Add commands to deploy to gh-pages, np. z użyciem gh-pages branch.
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force